### ISSUE TITLE
Replace SendGrid service

### ISSUE THREAD

**Issue by rignatus** [hacksoc-manchester/www#36]
# SendGrid replacement
* Replace with SMTP login to our personal mailbox
* Update README accordingly

**Comment by rignatus** [comment]
## Postponed
We have enough credit to continue until we scale it to ~thousands of users.

**Comment by andreimuntean** [comment]
"Replace with SMTP login to our personal mailbox" may be more difficult to setup and maintain than a (service-based) library like SendGrid.
